"use client";
import { useEffect, useState } from "react";
import { AccountBar, allowed, api, useAccount } from "../access-ui";
import type { User, Flow } from "../../lib/access";
type Task=Flow&{name:string;code:string;document_meta:string};
type Audit={id:string;at:string;actor:string;action:string;detail:string;sequence?:number};
type Snapshot={id:string;at:string;action:string;content:string;sha256:string};
function SnapshotComparison({snapshots}:{snapshots:Snapshot[]}){
 const [before,setBefore]=useState(1),[after,setAfter]=useState(0);
 if(snapshots.length<2)return <p>Save another snapshot to compare changes.</p>;
 const left=JSON.parse(snapshots[Math.min(before,snapshots.length-1)].content),right=JSON.parse(snapshots[Math.min(after,snapshots.length-1)].content);
 const describe=(d:Record<string,unknown>)=>{const fields=new Map<string,string>();fields.set("Title",String(d.name));fields.set("Version",String((d.documentMeta as Record<string,unknown>)?.versionLabel));fields.set("Document metadata",JSON.stringify(d.documentMeta,null,2));for(const [index,b] of ((d.contentSchema||[]) as Array<{id:string;type:string;text?:string;items?:string[];cells?:string[][];caption?:string;imageDataUrl?:string}>).entries()){fields.set(b.id||String(index),`${b.type}: ${b.text||b.items?.map(x=>"• "+x).join("\n")||b.cells?.map(row=>row.join(" | ")).join("\n")||b.caption||""}${b.type==="image"?"\nImage bytes: "+b.imageDataUrl?.length:""}`);}return fields;};
 const a=describe(left),b=describe(right);const changed=[...new Set([...a.keys(),...b.keys()])].filter(k=>a.get(k)!==b.get(k));
 return <div><div className="ac-snapshots"><label>Before<select value={Math.min(before,snapshots.length-1)} onChange={e=>setBefore(Number(e.target.value))}>{snapshots.map((s,i)=><option key={s.id} value={i}>{s.action} · {new Date(s.at).toLocaleString()}</option>)}</select></label><label>After<select value={Math.min(after,snapshots.length-1)} onChange={e=>setAfter(Number(e.target.value))}>{snapshots.map((s,i)=><option key={s.id} value={i}>{s.action} · {new Date(s.at).toLocaleString()}</option>)}</select></label></div>{!changed.length?<p>No text changes between these snapshots. Check the retained hashes/details below for non-text content.</p>:changed.map(k=><div key={k} className="ac-snapshots"><pre className="ac-wrap">{a.get(k)||"[Added]"}</pre><pre className="ac-wrap">{b.get(k)||"[Removed]"}</pre></div>)}</div>;
}
const labels:Record<string,string>={super_admin:"Super Admin",admin:"Admin",author:"Author / User",reviewer:"Reviewer",approver:"Approver / Director",auditor:"Read-only / Auditor"};
export default function AccessPage(){
 const u=useAccount();const manage=allowed(u,"super_admin","admin"),audit=allowed(u,"super_admin","admin","auditor");
 const [tab,setTab]=useState("tasks"),[data,setData]=useState<{workflows:Task[];users:User[];notifications:Array<{id:string;entity_id:string;message:string;read:number;at:string}>;unassigned:Array<{id:string;name:string;code:string}>}>({workflows:[],users:[],notifications:[],unassigned:[]});
 const [id,setId]=useState(""),[detail,setDetail]=useState<{events:Audit[];snapshots:Snapshot[];approval:Record<string,string>|null}>({events:[],snapshots:[],approval:null});
 const [note,setNote]=useState(""),[reviewerId,setReviewer]=useState(""),[approverId,setApprover]=useState(""),[authorId,setAuthor]=useState("");
 const [error,setError]=useState(""),[busy,setBusy]=useState(false),[users,setUsers]=useState<User[]>([]),[events,setEvents]=useState<Audit[]>([]),[before,setBefore]=useState<number|null>(null);
 const [account,setAccount]=useState({id:"",username:"",name:"",email:"",roles:["author"] as string[],active:1,password:""});
 const [currentPassword,setCurrentPassword]=useState(""),[newPassword,setNewPassword]=useState("");
 const task=data.workflows.find(t=>t.template_id===id);
 async function refresh(){const d=await api("/api/workflow");setData(d);if(id){const detail=await api(`/api/workflow?id=${encodeURIComponent(id)}`);setDetail(detail);}}
 useEffect(()=>{const tab=new URLSearchParams(window.location.search).get("tab");if(tab==="password")setTab("password");api("/api/workflow").then(setData).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(!id)return;let cancelled=false;api(`/api/workflow?id=${encodeURIComponent(id)}`).then(d=>{if(!cancelled)setDetail(d);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[id]);
 async function perform(fn:()=>Promise<void>){setBusy(true);setError("");try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const act=(action:string)=>perform(async()=>{await api("/api/workflow",{action,id,revision:task?.revision,note,reviewerId,approverId,authorId});setNote("");await refresh();});
 const select=(t:Task)=>{setId(t.template_id);setDetail({events:[],snapshots:[],approval:null});setNote("");setReviewer(t.reviewer_id||"");setApprover(t.approver_id||"");setAuthor(t.author_id);};
 const name=(id:string|null)=>data.users.find(u=>u.id===id)?.name||"Not assigned / inactive";
 const options=(roles:string[])=>data.users.filter(x=>allowed(x,...roles)).map(x=><option key={x.id} value={x.id}>{x.name}</option>);
 return <main className="ac-page"><header><a href="/" className="button secondary">← Forms & documents</a><AccountBar/></header><h1>Access & document control</h1><nav className="ac-tabs">{["tasks",...(manage?["users"]:[]),...(audit?["audit"]:[]),...(allowed(u,"super_admin")?["recovery"]:[]),"password"].map(t=><button className={tab===t?"button primary":"button secondary"} key={t} onClick={()=>{setTab(t);if(t==="users")void perform(async()=>setUsers((await api("/api/access")).users));if(t==="audit")void perform(async()=>{const d=await api("/api/access?resource=audit");setEvents(d.events);setBefore(d.next);});}}>{t==="tasks"?"Tasks & notifications":t==="users"?"User accounts":t==="audit"?"Audit history":t==="recovery"?"Backup & rollback":"My password"}</button>)}</nav>{error&&<p className="error-banner" role="alert">{error}</p>}
 {tab==="tasks"&&<><div className="ac-work"><section className="ac-panel"><h2>Documents</h2><button className="button secondary" disabled={busy} onClick={()=>void perform(refresh)}>Refresh</button>{!data.workflows.length&&<p>No documents assigned yet.</p>}{data.workflows.map(t=><button disabled={busy} key={t.template_id} className={`ac-task ${id===t.template_id?"selected":""}`} onClick={()=>select(t)}><strong>{t.code} · {t.name}</strong><span>v{JSON.parse(t.document_meta).versionLabel} · {t.status}</span>{((t.status==="Submitted for Review"&&t.reviewer_id===u.id)||(t.status==="Submitted for Approval"&&t.approver_id===u.id))&&<b>Your decision is needed</b>}</button>)}</section>
 <section className="ac-panel">{!task?<p>Select a document to view its decisions and history.</p>:<><h2>{task.name}</h2><p>{task.code} · {task.status} · Review round {task.round}</p><p>Author: {name(task.author_id)}<br/>Reviewer: {name(task.reviewer_id)}<br/>Approver: {name(task.approver_id)}</p><div className="ac-actions"><a className="button secondary" href={`/api/document/pdf?id=${id}`}>Open PDF</a><a className="button secondary" href={`/api/document/docx?id=${id}`}>Word</a>{task.author_id===u.id && allowed(u,"author","admin","super_admin") && ["Draft","Changes Requested","Approved","Superseded"].includes(task.status)&&<a className="button primary" href={`/?edit=${id}`}>{["Draft","Changes Requested"].includes(task.status)?"Edit draft":"Create next version"}</a>}</div>
 {!allowed(u,"auditor")&&<><label>Comment / decision note<textarea rows={4} maxLength={4000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Explain your decision or describe the required changes"/></label><div className="ac-actions"><button className="button secondary" disabled={busy||!note.trim()} onClick={()=>void act("comment")}>Add comment</button>
 {task.author_id===u.id&&["Draft","Changes Requested"].includes(task.status)&&<><label>Reviewer<select value={reviewerId} onChange={e=>setReviewer(e.target.value)}><option value="">Choose reviewer</option>{options(["reviewer","admin","super_admin"])}</select></label><label>Approver / Director<select value={approverId} onChange={e=>setApprover(e.target.value)}><option value="">Choose approver</option>{options(["approver","super_admin"])}</select></label><button className="button primary" disabled={busy||!note||!reviewerId||!approverId} onClick={()=>void act("submit")}>Submit for review</button></>}
 {task.author_id===u.id&&task.status==="Recommended for Approval"&&<button className="button primary" disabled={busy||!note} onClick={()=>void act("submit-approval")}>Submit to Director</button>}
 {task.reviewer_id===u.id&&task.status==="Submitted for Review"&&<button className="button primary" disabled={busy||!note} onClick={()=>void act("recommend")}>Recommend approval</button>}
 {task.approver_id===u.id&&task.status==="Submitted for Approval"&&<button className="button primary" disabled={busy||!note} onClick={()=>void act("approve")}>Approve & lock version</button>}
 {((task.reviewer_id===u.id&&task.status==="Submitted for Review")||(task.approver_id===u.id&&task.status==="Submitted for Approval")||(manage&&["Submitted for Review","Recommended for Approval","Submitted for Approval"].includes(task.status)))&&<button className="button secondary" disabled={busy||!note} onClick={()=>void act("changes")}>Request changes</button>}
 {manage&&["Approved","Superseded"].includes(task.status)&&<button className="button secondary" disabled={busy||!note} onClick={()=>void act("archive")}>Archive version</button>}
 {manage&&["Draft","Changes Requested"].includes(task.status)&&<><label>Assign author<select value={authorId} onChange={e=>setAuthor(e.target.value)}><option value="">Choose author</option>{options(["author","admin","super_admin"])}</select></label><button className="button secondary" disabled={busy||!note||!authorId} onClick={()=>void act("assign")}>Reassign</button></>}
 </div></>}
 {detail.approval&&<details><summary>Approved file hashes</summary><pre className="ac-wrap">{JSON.stringify(detail.approval,null,2)}</pre></details>}
 <h3>Saved content & comparison</h3><SnapshotComparison key={id+detail.snapshots[0]?.id} snapshots={detail.snapshots}/><p>Full retained snapshots, including non-text details:</p><div className="ac-snapshots">{detail.snapshots.map(s=><details key={s.id}><summary>{s.action} · {new Date(s.at).toLocaleString()}</summary><small>SHA-256 {s.sha256}</small><pre className="ac-wrap">{JSON.stringify(JSON.parse(s.content),null,2)}</pre></details>)}</div>
 <h3>Decision history</h3>{detail.events.map(e=><article className="ac-event" key={e.id}><strong>{e.action} · {e.actor}</strong><small>{new Date(e.at).toLocaleString()}</small><pre className="ac-wrap">{JSON.stringify(JSON.parse(e.detail),null,2)}</pre></article>)}</>}</section>
 <section className="ac-panel"><h2>Notifications</h2>{!data.notifications.length&&<p>No notifications yet.</p>}{data.notifications.map(n=><button className={`ac-task ${!n.read?"selected":""}`} key={n.id} onClick={()=>void perform(async()=>{const t=data.workflows.find(t=>t.template_id===n.entity_id);if(t)select(t);await api("/api/workflow",{action:"read",id:n.id});await refresh();})}><strong>{n.message}</strong><small>{new Date(n.at).toLocaleString()}</small>{!n.read&&<span>Unread</span>}</button>)}</section></div>
 {manage&&data.unassigned.length>0&&<section className="ac-panel"><h2>Existing documents awaiting assignment</h2><p>Assign an author before controlled review. Original metadata is retained in a snapshot; old approval labels are not treated as verified decisions.</p><label>Author<select value={authorId} onChange={e=>setAuthor(e.target.value)}><option value="">Choose author</option>{options(["author","admin","super_admin"])}</select></label><label>Assignment reason<input value={note} onChange={e=>setNote(e.target.value)}/></label>{data.unassigned.map(t=><div className="ac-actions" key={t.id}><span>{t.code} · {t.name}</span><button className="button secondary" disabled={busy||!authorId||!note} onClick={()=>void perform(async()=>{await api("/api/workflow",{action:"assign-legacy",id:t.id,authorId,note});await refresh();})}>Assign for review</button></div>)}</section>}</>}
 {tab==="users"&&<div className="ac-work ac-two"><section className="ac-panel"><h2>User accounts</h2><button className="button secondary" onClick={()=>setAccount({id:"",username:"",name:"",email:"",roles:["author"],active:1,password:""})}>New user</button>{users.map(person=><button className="ac-task" key={person.id} onClick={()=>setAccount({...person,password:""})}><strong>{person.name} ({person.username})</strong><span>{person.roles.map(r=>labels[r]).join(", ")} · {person.active?"Active":"Disabled"}</span></button>)}</section><form className="ac-panel" onSubmit={e=>{e.preventDefault();void perform(async()=>{await api("/api/access",{...account,action:account.id?"update":"create"});setUsers((await api("/api/access")).users);setAccount({...account,password:""});});}}><h2>{account.id?"Manage account":"Create account"}</h2><label>Username<input required disabled={!!account.id} value={account.username} onChange={e=>setAccount({...account,username:e.target.value})}/></label><label>Full name<input required value={account.name} onChange={e=>setAccount({...account,name:e.target.value})}/></label><label>Email (optional)<input type="email" value={account.email} onChange={e=>setAccount({...account,email:e.target.value})}/></label><fieldset><legend>Roles</legend>{Object.entries(labels).filter(([r])=>r!=="super_admin"&&(r!=="admin"||allowed(u,"super_admin"))).map(([r,label])=><label className="ac-check" key={r}><input type="checkbox" checked={account.roles.includes(r)} onChange={e=>setAccount({...account,roles:e.target.checked?[...account.roles,r]:account.roles.filter(x=>x!==r)})}/>{label}</label>)}</fieldset><label className="ac-check"><input type="checkbox" checked={!!account.active} onChange={e=>setAccount({...account,active:e.target.checked?1:0})}/>Active account</label><label>Temporary password<input type="password" autoComplete="new-password" minLength={12} maxLength={128} required={!account.id} value={account.password} onChange={e=>setAccount({...account,password:e.target.value})}/></label><div className="ac-actions"><button className="button primary" disabled={busy||account.roles.includes("super_admin")}>{account.id?"Save permissions":"Create user"}</button>{account.id&&<button type="button" className="button secondary" disabled={busy||account.password.length<12||account.roles.includes("super_admin")} onClick={()=>void perform(async()=>{await api("/api/access",{action:"reset",id:account.id,password:account.password});setAccount({...account,password:""});})}>Reset password</button>}</div><p>Permission changes and password resets end that user's sessions immediately. The Super Admin is protected and recoverable from the VM console.</p></form></div>}
 {tab==="audit"&&<section className="ac-panel"><h2>Audit history</h2><p>Newest 500 events. Load older events for earlier history. Exports contain the newest 500; use the before parameter shown below for earlier batches.</p><div className="ac-actions"><a className="button secondary" href="/api/access?resource=audit&format=csv">Export CSV</a><a className="button secondary" href="/api/access?resource=audit&format=pdf">Export PDF</a>{before&&<button className="button secondary" disabled={busy} onClick={()=>void perform(async()=>{const d=await api(`/api/access?resource=audit&before=${before}`);setEvents([...events,...d.events]);setBefore(d.next);})}>Load older events (before {before})</button>}</div>{events.map(e=><article className="ac-event" key={e.id}><strong>#{e.sequence} {e.action} · {e.actor}</strong><small>{new Date(e.at).toLocaleString()}</small><pre className="ac-wrap">{e.detail}</pre></article>)}</section>}
 {tab==="recovery"&&allowed(u,"super_admin")&&<section className="ac-panel"><h2>Backup & rollback</h2><p>Run recovery from the Ubuntu terminal. It remains available even when this application cannot open. Keep restore points off the VM as well.</p><h3>Create a restore point</h3><pre className="ac-wrap">bash deploy/local/create-restore-point.sh</pre><h3>Roll back the application, keeping current records</h3><pre className="ac-wrap">bash deploy/local/rollback-local.sh --acknowledge-legacy-access</pre><p>Returning to v0.4.2 restores its old shared login and removes enforcement of individual permissions and approvals. Keep the VM isolated while rolled back.</p><h3>Restore the matching older data too</h3><pre className="ac-wrap">bash deploy/local/rollback-local.sh --restore-data --acknowledge-legacy-access</pre><p>This returns active records to the saved date. Newer data is moved to a rescue folder, not merged. See UPGRADE_0_5_0.md for exact installation, recovery and Super Admin reset instructions.</p></section>}
 {tab==="password"&&<form className="ac-panel ac-narrow" onSubmit={e=>{e.preventDefault();void perform(async()=>{await api("/api/auth",{action:"password",currentPassword,password:newPassword});window.location.assign("/");});}}><h2>Change password</h2><label>Current password<input type="password" required autoComplete="current-password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></label><label>New password<input type="password" required autoComplete="new-password" minLength={12} maxLength={128} value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label><button className="button primary" disabled={busy}>Change password & sign out</button></form>}
 </main>;
}
