"use client";
import { createContext, useContext, useEffect, useState, type ReactNode } from "react";
import { Bell, LogOut } from "lucide-react";
import type { User } from "../lib/access";
export const allowed=(u:User,...roles:string[])=>u.roles.some(r=>roles.includes(r));
const Account=createContext<User|null>(null);
export const useAccount=()=>useContext(Account)!;
export async function api(path:string,body?:unknown){const r=await fetch(path,{cache:"no-store",...(body?{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}:{})});const text=await r.text();let data;try{data=JSON.parse(text);}catch{throw Error(`Service unavailable (HTTP ${r.status}). Your input has not been cleared.`);}if(!r.ok){const error=Object.assign(Error(data.error||"Request failed"),{status:r.status});throw error;}return data;}
export function AccessGate({children}:{children:ReactNode}){
 const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState(false),[username,setUsername]=useState(""),[password,setPassword]=useState(""),[replacement,setReplacement]=useState("");
 useEffect(()=>{api("/api/auth").then(d=>setUser(d.user)).catch(()=>{}).finally(()=>setLoading(false));},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{if(user?.must_change){await api("/api/auth",{action:"password",currentPassword:password,password:replacement});setUser(null);setPassword("");setReplacement("");setError("Password changed. Sign in with your new password.");}else{const d=await api("/api/auth",{action:"login",username,password});setUser(d.user);setPassword("");}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(loading)return <main className="ac-login"><p>Opening CCPL FormFlow…</p></main>;
 if(!user || user.must_change)return <main className="ac-login"><form onSubmit={submit}><span className="brand-mark">CF</span><h1>{user?"Set your password":"Sign in to CCPL FormFlow"}</h1><p>{user?"Replace your temporary password to continue.":"Use your individual account."}</p>{!user&&<label>Username<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required /></label>}<label>{user?"Temporary password":"Password"}<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required /></label>{user&&<label>New password (12–128 characters)<input type="password" autoComplete="new-password" minLength={12} maxLength={128} value={replacement} onChange={e=>setReplacement(e.target.value)} required /></label>}{error&&<p role="alert">{error}</p>}<button className="button primary" disabled={busy}>{busy?"Please wait…":user?"Change password":"Sign in"}</button><small>First installation or locked out? The VM administrator can use the offline account setup/recovery command.</small></form></main>;
 return <Account.Provider value={user}>{children}</Account.Provider>;
}
export function AccountBar(){const u=useAccount();const [count,setCount]=useState(0);useEffect(()=>{const refresh=()=>api("/api/workflow?poll=1").then(d=>setCount(d.unread)).catch(e=>{if(e.status===401||e.status===428)window.location.reload();});void refresh();const t=setInterval(()=>{if(document.visibilityState==="visible")void refresh();},30000);return()=>clearInterval(t);},[]);return <div className="ac-account"><a href="/access" className="button secondary"><Bell size={16}/>Tasks {count>0&&<b>{count}</b>}</a><a href="/access?tab=password">{u.name}</a><button className="icon-button" aria-label="Sign out" onClick={async()=>{await api("/api/auth",{action:"logout"});window.location.assign("/");}}><LogOut size={17}/></button></div>;}
