"use client";

import {
  ArrowDown, ArrowLeft, ArrowUp, CalendarDays, Check, CheckCircle2,
  ChevronDown, ChevronRight, Copy, Download, Edit3, Eye, FileCheck2,
  FileDown, FilePlus2, FileSpreadsheet, FileText, Filter, GripVertical,
  History, LayoutDashboard, ListFilter, Loader2, LockKeyhole, MoreHorizontal,
  Plus, Save, Search, Settings2, ShieldCheck, Sparkles, Trash2, UploadCloud, X,
} from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { DocumentBuilder, type DocumentBlock } from "./document-builder";
import { DocumentRegister } from "./document-register";
import { AccountBar, allowed, useAccount } from "./access-ui";
import type { Flow } from "../lib/access";

type FieldType = "text" | "number" | "date" | "dropdown" | "checkbox" | "radio" | "textarea" | "signature" | "file";
type FormField = { id: string; label: string; type: FieldType; required: boolean; section: string; placeholder?: string; defaultValue?: string | boolean; options?: string[]; keySummary?: boolean; validation?: { regex?: string; min?: number; max?: number; minDate?: string; maxDate?: string } };
type DocumentMeta = { outputStyle: "operational-form" | "controlled-document"; documentType: string; versionLabel: string; classification: string; documentOwner: string; documentStatus: string; effectiveDate: string; preparedBy: string; reviewedBy: string; approvedBy: string; subtitle: string };
type Template = { workflow?: Flow; id: string; name: string; code: string; version: number; category: string; description: string; fields: FormField[]; contentSchema: DocumentBlock[]; changeDescription: string; revisionDate: string; baseTemplateId: string; sourceImportId: string; sourceFileName: string; sourceFileHash: string; importSummary: Record<string, number>; documentMeta: DocumentMeta; numberingPattern: string; status: string; createdBy: string; createdAt: string; updatedAt: string };
type Submission = { id: string; templateId: string; uniqueNumber: string; data: Record<string, string | boolean>; status: string; createdBy: string; createdAt: string; updatedAt: string; revision: number; pdfPath: string };
type AuditItem = { id: string; changed_by: string; timestamp: string; summary: string; diff_json: string };
type ModuleKind = "forms" | "documents";
type View = "forms" | "form-builder" | "form-register" | "documents" | "document-builder" | "document-register" | "filler" | "detail";
type BuilderState = { editingTemplateId?: string; expectedRevision?: number; name: string; code: string; category: string; description: string; numberingPattern: string; baseTemplateId: string; sourceImportId: string; sourceFileName: string; sourceFileHash: string; importSummary: Record<string, number>; documentMeta: DocumentMeta; changeDescription: string; revisionDate: string };

const fieldTypes: Array<{ value: FieldType; label: string }> = [
  { value: "text", label: "Short text" }, { value: "number", label: "Number" },
  { value: "date", label: "Date" }, { value: "dropdown", label: "Dropdown" },
  { value: "checkbox", label: "Checkbox" }, { value: "radio", label: "Radio group" },
  { value: "textarea", label: "Long text" }, { value: "signature", label: "Signature" },
  { value: "file", label: "File upload" },
];
const clientId = () => `field_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
const emptyField = (): FormField => ({ id: clientId(), label: "", type: "text", required: false, section: "General information", placeholder: "", defaultValue: "", options: [], keySummary: false, validation: {} });
const defaultDocumentMeta = (module: ModuleKind): DocumentMeta => ({ outputStyle: module === "forms" ? "operational-form" : "controlled-document", documentType: module === "forms" ? "FORM" : "POLICY", versionLabel: module === "forms" ? "1.0" : "0.1", classification: "INTERNAL", documentOwner: "Quality Management", documentStatus: "DRAFT FOR APPROVAL", effectiveDate: "", preparedBy: "Yasir Khan", reviewedBy: "", approvedBy: "Director", subtitle: "" });
const emptyBuilder = (module: ModuleKind): BuilderState => ({ name: "", code: "", category: "Quality", description: "", numberingPattern: module === "forms" ? "CCPL-FRM-{CODE}-{YYYY}-{SEQ:4}" : "CCPL-DOC-{CODE}-{YYYY}-{SEQ:4}", baseTemplateId: "", sourceImportId: "", sourceFileName: "", sourceFileHash: "", importSummary: {}, documentMeta: defaultDocumentMeta(module), changeDescription: "Initial issue", revisionDate: "" });
const formatDate = (value: string, includeTime = false) => new Date(value).toLocaleDateString("en-GB", includeTime ? { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" } : { day: "2-digit", month: "short", year: "numeric" });
const initials = (name: string) => name.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase();

function StatusBadge({ status }: { status: string }) { return <span className={`status status-${status.toLowerCase()}`}><span />{status}</span>; }
function Toast({ message, onClose }: { message: string; onClose: () => void }) {
  useEffect(() => { const timeout = setTimeout(onClose, 4200); return () => clearTimeout(timeout); }, [onClose]);
  return <div className="toast"><CheckCircle2 size={18} />{message}<button onClick={onClose} aria-label="Close notification"><X size={16} /></button></div>;
}
function PageHeading({ eyebrow, title, description, actions }: { eyebrow?: string; title: string; description?: string; actions?: React.ReactNode }) {
  return <div className="page-heading"><div>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1>{description && <p>{description}</p>}</div>{actions && <div className="heading-actions">{actions}</div>}</div>;
}

export default function Home() {
  const account=useAccount();
  const [view, setView] = useState<View>("forms");
  const [templates, setTemplates] = useState<Template[]>([]);
  const [submissions, setSubmissions] = useState<Submission[]>([]);
  const [user, setUser] = useState({ name: account.name, email: account.email });
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const [selectedTemplateId, setSelectedTemplateId] = useState("");
  const [selectedSubmissionId, setSelectedSubmissionId] = useState("");
  const [audit, setAudit] = useState<AuditItem[]>([]);
  const [search, setSearch] = useState(""); const [statusFilter, setStatusFilter] = useState("All");
  const [formValues, setFormValues] = useState<Record<string, string | boolean>>({});
  const [formErrors, setFormErrors] = useState<Record<string, string>>({});
  const [editingSubmission, setEditingSubmission] = useState(false); const [detailStatus, setDetailStatus] = useState("Draft");
  const [builder, setBuilder] = useState<BuilderState>(emptyBuilder("forms"));
  const [builderFields, setBuilderFields] = useState<FormField[]>([]);
  const [documentBlocks, setDocumentBlocks] = useState<DocumentBlock[]>([]);
  const [fieldDraft, setFieldDraft] = useState<FormField>(emptyField());
  const [editingFieldIndex, setEditingFieldIndex] = useState<number | null>(null);
  const [draggedIndex, setDraggedIndex] = useState<number | null>(null);

  const loadData = useCallback(async () => {
    setLoading(true); setError("");
    try {
      const response = await fetch("/api/app?resource=dashboard", { cache: "no-store" }); const data = await response.json();
      if (!response.ok) throw new Error(data.error || "Unable to load form data");
      setTemplates(data.templates || []); setSubmissions(data.submissions || []); if (data.user) setUser(data.user);
      const editId=new URLSearchParams(window.location.search).get("edit");const editing=data.templates?.find((t:Template)=>t.id===editId);
      if(editing && editing.workflow?.author_id===data.user.id && ["Draft","Changes Requested","Approved","Superseded"].includes(editing.workflow.status)){
        const draft=["Draft","Changes Requested"].includes(editing.workflow.status);
        setBuilder({...editing,baseTemplateId:draft?"":editing.id,editingTemplateId:draft?editing.id:"",expectedRevision:editing.workflow.revision,documentMeta:{...editing.documentMeta,documentStatus:"DRAFT",preparedBy:data.user.name,reviewedBy:"",approvedBy:""},changeDescription:draft?editing.changeDescription:""});
        setDocumentBlocks(editing.contentSchema);setView("document-builder");window.history.replaceState(null,"","/");
      }
      const firstForm = data.templates?.find((item: Template) => item.documentMeta?.outputStyle !== "controlled-document");
      if (data.templates?.length) setSelectedTemplateId((current) => current || firstForm?.id || data.templates[0].id);
    } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load form data"); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => {
    // Data is synchronized from the persistent workspace database on first load.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void loadData();
  }, [loadData]);

  const selectedTemplate = useMemo(() => templates.find((item) => item.id === selectedTemplateId) || templates[0], [templates, selectedTemplateId]);
  const selectedSubmission = useMemo(() => submissions.find((item) => item.id === selectedSubmissionId), [submissions, selectedSubmissionId]);
  const latestTemplates = useMemo(() => { const latest = new Map<string, Template>(); templates.forEach((item) => { const existing = latest.get(item.code); if (!existing || item.version > existing.version) latest.set(item.code, item); }); return Array.from(latest.values()); }, [templates]);
  const formTemplates = useMemo(() => latestTemplates.filter((item) => item.documentMeta.outputStyle !== "controlled-document"), [latestTemplates]);
  const documentTemplates = useMemo(() => latestTemplates.filter((item) => item.documentMeta.outputStyle === "controlled-document"), [latestTemplates]);
  const formTemplateIds = useMemo(() => new Set(templates.filter((item) => item.documentMeta.outputStyle !== "controlled-document").map((item) => item.id)), [templates]);
  const formSubmissions = useMemo(() => submissions.filter((item) => formTemplateIds.has(item.templateId)), [submissions, formTemplateIds]);
  const documentVersions = useMemo(() => templates.filter((item) => item.documentMeta.outputStyle === "controlled-document"), [templates]);
  const selectedFormTemplate = formTemplates.find((item) => item.id === selectedTemplateId) || formTemplates[0];
  const templateCounts = useMemo(() => submissions.reduce<Record<string, number>>((counts, item) => { counts[item.templateId] = (counts[item.templateId] || 0) + 1; return counts; }, {}), [submissions]);
  const go = (next: View) => { setError(""); setView(next); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const moduleFor = (template?: Template): ModuleKind => template?.documentMeta.outputStyle === "controlled-document" ? "documents" : "forms";

  const openFiller = (template: Template) => {
    if(!allowed(account,"super_admin","admin","author")){setError("This account cannot fill forms.");return;}
    setSelectedTemplateId(template.id); const defaults: Record<string, string | boolean> = {};
    template.fields.forEach((field) => { defaults[field.id] = field.defaultValue ?? (field.type === "checkbox" ? false : ""); });
    setFormValues(defaults); setFormErrors({}); go("filler");
  };
  const openRegister = (module: ModuleKind, template?: Template) => {
    const fallback = module === "forms" ? formTemplates[0] : documentTemplates[0];
    setSelectedTemplateId(template?.id || fallback?.id || "");
    setSearch(""); setStatusFilter("All"); go(module === "forms" ? "form-register" : "document-register");
  };
  const openBuilder = (template?: Template, requestedModule: ModuleKind = "forms") => {
    const moduleKind = template ? moduleFor(template) : requestedModule;
    if(!allowed(account,"super_admin","admin",...(moduleKind==="documents"?["author"]:[]))){setError("This account cannot create or edit templates.");return;}
    if(template && moduleKind==="documents"){
      if(!template.workflow){setError("Assign this legacy document in Tasks & notifications first.");return;}
      if(template.workflow.author_id!==account.id || !["Draft","Changes Requested","Approved","Superseded"].includes(template.workflow.status)){setError("Only the assigned author can edit a draft or create a new version.");return;}
    }
    if (template) {
      setBuilder({ name: template.name, code: template.code, category: template.category, description: template.description, numberingPattern: template.numberingPattern, baseTemplateId: template.workflow && ["Draft","Changes Requested"].includes(template.workflow.status) ? "" : template.id, editingTemplateId: template.workflow && ["Draft","Changes Requested"].includes(template.workflow.status) ? template.id : "", expectedRevision: template.workflow?.revision, sourceImportId: template.sourceImportId, sourceFileName: template.sourceFileName, sourceFileHash: template.sourceFileHash, importSummary: { ...template.importSummary }, documentMeta: { ...template.documentMeta, ...(moduleKind==="documents"?{documentStatus:"DRAFT",preparedBy:account.name,reviewedBy:"",approvedBy:""}:{}) }, changeDescription: template.workflow && ["Draft","Changes Requested"].includes(template.workflow.status) ? template.changeDescription : "", revisionDate: "" });
      setBuilderFields(template.fields.map((field) => ({ ...field, id: clientId() })));
      setDocumentBlocks(template.contentSchema.map((block) => ({ ...block, cells: block.cells?.map((row) => [...row]), items: block.items ? [...block.items] : undefined })));
    } else { setBuilder({...emptyBuilder(moduleKind),documentMeta:{...defaultDocumentMeta(moduleKind),preparedBy:account.name,approvedBy:"",reviewedBy:""}}); setBuilderFields([]); setDocumentBlocks([]); }
    setFieldDraft(emptyField()); setEditingFieldIndex(null); go(moduleKind === "forms" ? "form-builder" : "document-builder");
  };
  const openDetail = async (submission: Submission) => {
    setSelectedSubmissionId(submission.id); setSelectedTemplateId(submission.templateId); setFormValues({ ...submission.data }); setDetailStatus(submission.status); setEditingSubmission(false); setAudit([]); go("detail");
    try { const response = await fetch(`/api/app?resource=submission&id=${submission.id}`, { cache: "no-store" }); const data = await response.json(); if (response.ok) setAudit(data.audit || []); } catch { /* optional */ }
  };
  const validateClient = (template: Template, values: Record<string, string | boolean>) => {
    const errors: Record<string, string> = {};
    template.fields.forEach((field) => {
      const value = values[field.id]; const empty = value === undefined || value === null || value === "" || (field.type === "checkbox" && value !== true);
      if (field.required && empty) errors[field.id] = `${field.label} is required`;
      if (!empty && field.validation?.regex) { try { if (!new RegExp(field.validation.regex).test(String(value))) errors[field.id] = "Value does not match the required format"; } catch { /* server catches malformed rules */ } }
      if (!empty && field.validation?.min !== undefined) { const comparable = field.type === "number" ? Number(value) : String(value).length; if (comparable < field.validation.min) errors[field.id] = field.type === "number" ? `Minimum value is ${field.validation.min}` : `Enter at least ${field.validation.min} characters`; }
      if (!empty && field.validation?.max !== undefined) { const comparable = field.type === "number" ? Number(value) : String(value).length; if (comparable > field.validation.max) errors[field.id] = field.type === "number" ? `Maximum value is ${field.validation.max}` : `Enter no more than ${field.validation.max} characters`; }
    });
    setFormErrors(errors); return Object.keys(errors).length === 0;
  };
  const submitForm = async (status: "Draft" | "Submitted") => {
    if (!selectedTemplate || !validateClient(selectedTemplate, formValues)) return; setBusy(true); setError("");
    try {
      const response = await fetch("/api/app", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "create-submission", templateId: selectedTemplate.id, data: formValues, status }) }); const data = await response.json();
      if (!response.ok) { if (data.errors) setFormErrors(data.errors); throw new Error(data.error || "Unable to save submission"); }
      await loadData(); setNotice(`${data.submission.uniqueNumber} saved as ${status}`); setSelectedSubmissionId(data.submission.id); setSelectedTemplateId(selectedTemplate.id); go("form-register");
    } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to save submission"); } finally { setBusy(false); }
  };
  const saveEditedSubmission = async () => {
    if (!selectedTemplate || !selectedSubmission || !validateClient(selectedTemplate, formValues)) return; setBusy(true); setError("");
    try {
      const response = await fetch("/api/app", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "update-submission", id: selectedSubmission.id, data: formValues, status: detailStatus }) }); const data = await response.json();
      if (!response.ok) throw new Error(data.error || "Unable to update submission"); await loadData(); setNotice(`${selectedSubmission.uniqueNumber} updated - revision ${data.submission.revision}`); setEditingSubmission(false); await openDetail(data.submission);
    } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to update submission"); } finally { setBusy(false); }
  };
  const saveTemplate = async () => {
    const isDocument = builder.documentMeta.outputStyle === "controlled-document";
    if (!builder.name.trim() || !builder.code.trim() || (!isDocument && !builderFields.length) || (isDocument && !documentBlocks.length)) { setError(isDocument ? "Add a document title, document ID, and at least one content block before saving." : "Add a form name, template code, and at least one field before saving."); return; }
    if (isDocument && builder.baseTemplateId && !builder.changeDescription.trim()) { setError("Enter a change description before saving a new document version."); return; }
    setBusy(true); setError("");
    try {
      const response = await fetch("/api/app", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: builder.editingTemplateId ? "update-document" : "create-template", ...builder, fields: isDocument ? [] : builderFields, contentSchema: isDocument ? documentBlocks : [] }) }); const data = await response.json();
      if (!response.ok) throw new Error(data.error || "Unable to save template"); await loadData(); setSelectedTemplateId(data.template.id); setNotice(`${data.template.name} version ${data.template.version} is available`); go(moduleFor(data.template) === "forms" ? "forms" : "documents");
    } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to save template"); } finally { setBusy(false); }
  };
  const editField = (index: number) => { setEditingFieldIndex(index); setFieldDraft({ ...builderFields[index], options: [...(builderFields[index].options || [])], validation: { ...(builderFields[index].validation || {}) } }); };
  const persistFieldDraft = () => {
    if (!fieldDraft.label.trim()) { setError("Enter a field label before adding it."); return; } setError("");
    if (editingFieldIndex === null) setBuilderFields((current) => [...current, fieldDraft]); else setBuilderFields((current) => current.map((field, index) => index === editingFieldIndex ? fieldDraft : field));
    setEditingFieldIndex(null); setFieldDraft(emptyField());
  };
  const moveField = (from: number, to: number) => { if (to < 0 || to >= builderFields.length || from === to) return; setBuilderFields((current) => { const next = [...current]; const [moved] = next.splice(from, 1); next.splice(to, 0, moved); return next; }); };
  const formNav = [{ id: "forms" as View, label: "Available forms", icon: LayoutDashboard }, { id: "form-builder" as View, label: "Form builder", icon: FilePlus2 }, { id: "form-register" as View, label: "Form registers", icon: FileSpreadsheet }];
  const documentNav = [{ id: "documents" as View, label: "Document library", icon: FileText }, { id: "document-builder" as View, label: "Document builder", icon: FilePlus2 }, { id: "document-register" as View, label: "Document register", icon: FileSpreadsheet }];
  const openNav = (item: { id: View }) => {
    if (item.id === "form-builder") openBuilder(undefined, "forms");
    else if (item.id === "document-builder") openBuilder(undefined, "documents");
    else if (item.id === "form-register") openRegister("forms");
    else if (item.id === "document-register") openRegister("documents");
    else go(item.id);
  };
  const detailModule = moduleFor(selectedTemplate);
  const navActive = (id: View) => view === id || (view === "filler" && id === "forms") || (view === "detail" && id === (detailModule === "forms" ? "form-register" : "document-register"));
  const breadcrumb: Record<View, string> = { forms: "Available forms", "form-builder": "Form builder", "form-register": "Form registers", documents: "Document library", "document-builder": "Document builder", "document-register": "Document register", filler: "Fill form", detail: detailModule === "forms" ? "Form record" : "Document record" };

  if (loading) return <div className="loading-screen"><div className="brand-mark">CF</div><Loader2 className="spin" /><p>Preparing your controlled forms...</p></div>;
  return <div className="app-shell">
    <aside className="sidebar">
      <button className="brand" onClick={() => go("forms")}><span className="brand-mark">CF</span><span><strong>CCPL</strong><small>FormFlow</small></span></button>
      <nav><a href="/access" className="button secondary">Tasks, users & audit history</a><p className="nav-label">Forms</p>{formNav.filter(item=>item.id!=="form-builder"||allowed(account,"super_admin","admin")).map((item) => { const Icon = item.icon; const active = navActive(item.id); return <button key={item.id} className={active ? "active" : ""} onClick={() => openNav(item)}><Icon size={18} />{item.label}{active && <ChevronRight size={15} className="nav-arrow" />}</button>; })}<p className="nav-label nav-label-spaced">Controlled documents</p>{documentNav.filter(item=>item.id!=="document-builder"||allowed(account,"super_admin","admin","author")).map((item) => { const Icon = item.icon; const active = navActive(item.id); return <button key={item.id} className={active ? "active" : ""} onClick={() => openNav(item)}><Icon size={18} />{item.label}{active && <ChevronRight size={15} className="nav-arrow" />}</button>; })}</nav>
      <div className="sidebar-note"><ShieldCheck size={18} /><div><strong>Controlled workspace</strong><span>Changes are attributed and logged.</span></div></div>
      <div className="sidebar-user"><span className="avatar">{initials(user.name)}</span><div><strong>{user.name}</strong><span><span className="online-dot" />Signed in</span></div><MoreHorizontal size={18} /></div>
    </aside>
    <main className="main-area">
      <header className="topbar"><div className="mobile-brand"><span className="brand-mark">CF</span><strong>FormFlow</strong></div><div className="breadcrumb"><span>CCPL Workspace</span><ChevronRight size={14} /><strong>{breadcrumb[view]}</strong></div><div className="top-actions"><button className="icon-button" aria-label="User access and document tasks" onClick={()=>window.location.assign("/access")}><Settings2 size={18} /></button><AccountBar/></div></header>
      <div className="mobile-tabs">{[formNav[0], formNav[2], documentNav[0], documentNav[2]].map((item) => { const Icon = item.icon; return <button key={item.id} className={navActive(item.id) ? "active" : ""} onClick={() => openNav(item)}><Icon size={18} /><span>{item.label}</span></button>; })}</div>
      {error && <div className="error-banner"><span>{error}</span><button onClick={() => setError("")}><X size={16} /></button></div>}
      {view === "forms" && <Dashboard templates={formTemplates} submissions={formSubmissions} counts={templateCounts} user={user} onBuild={() => openBuilder(undefined, "forms")} onFill={openFiller} onRegister={(template) => openRegister("forms", template)} onRevise={(template) => openBuilder(template, "forms")} onDetail={openDetail} />}
      {view === "documents" && <DocumentLibrary templates={documentTemplates} versionCount={documentVersions.length} onBuild={() => openBuilder(undefined, "documents")} onRegister={() => openRegister("documents")} onRevise={(template) => openBuilder(templates.find(t=>t.id===template.id)!, "documents")} />}
      {view === "form-builder" && <Builder module="forms" builder={builder} setBuilder={setBuilder} fields={builderFields} fieldDraft={fieldDraft} setFieldDraft={setFieldDraft} editingIndex={editingFieldIndex} setEditingIndex={setEditingFieldIndex} onEditField={editField} onSaveField={persistFieldDraft} onDeleteField={(index) => setBuilderFields((current) => current.filter((_, currentIndex) => currentIndex !== index))} onMoveField={moveField} draggedIndex={draggedIndex} setDraggedIndex={setDraggedIndex} onSave={saveTemplate} busy={busy} />}
      {view === "document-builder" && <DocumentBuilder builder={builder} setBuilder={setBuilder} blocks={documentBlocks} setBlocks={setDocumentBlocks} onSave={saveTemplate} busy={busy} />}
      {view === "filler" && selectedTemplate && <Filler template={selectedTemplate} values={formValues} setValues={setFormValues} errors={formErrors} onBack={() => go("forms")} onSubmit={submitForm} busy={busy} />}
      {view === "form-register" && selectedFormTemplate && <Register module="forms" templates={formTemplates} selectedTemplate={selectedFormTemplate} submissions={formSubmissions} search={search} setSearch={setSearch} statusFilter={statusFilter} setStatusFilter={setStatusFilter} onTemplateChange={setSelectedTemplateId} onFill={openFiller} onDetail={openDetail} />}
      {view === "document-register" && documentTemplates.length > 0 && <DocumentRegister templates={templates.filter((template) => template.documentMeta.outputStyle === "controlled-document")} onBuild={() => openBuilder(undefined, "documents")} onRevise={(template) => openBuilder(templates.find(t=>t.id===template.id)!, "documents")} />}
      {(view === "form-register" && !selectedFormTemplate) && <EmptyRegister module="forms" onBuild={() => openBuilder(undefined, "forms")} />}
      {(view === "document-register" && !documentTemplates.length) && <EmptyRegister module="documents" onBuild={() => openBuilder(undefined, "documents")} />}
      {view === "detail" && selectedTemplate && selectedSubmission && <SubmissionDetail template={selectedTemplate} submission={selectedSubmission} audit={audit} values={formValues} setValues={setFormValues} errors={formErrors} editing={editingSubmission} setEditing={setEditingSubmission} status={detailStatus} setStatus={setDetailStatus} onBack={() => go(moduleFor(selectedTemplate) === "forms" ? "form-register" : "document-register")} onSave={saveEditedSubmission} busy={busy} />}
    </main>{notice && <Toast message={notice} onClose={() => setNotice("")} />}
  </div>;
}

function Dashboard({ templates, submissions, counts, user, onBuild, onFill, onRegister, onRevise, onDetail }: { templates: Template[]; submissions: Submission[]; counts: Record<string, number>; user: { name: string }; onBuild: () => void; onFill: (template: Template) => void; onRegister: (template?: Template) => void; onRevise: (template: Template) => void; onDetail: (submission: Submission) => void }) {
  const thisMonth = submissions.filter((item) => new Date(item.createdAt).getMonth() === new Date().getMonth()).length; const approved = submissions.filter((item) => item.status === "Approved").length; const recent = submissions.slice(0, 5);
  return <div className="content dashboard-page"><PageHeading eyebrow="Controlled forms workspace" title={`Good afternoon, ${user.name.split(" ")[0]}`} description="Create controlled forms, issue traceable records, and keep every change accountable." actions={<button className="button primary" onClick={onBuild}><Plus size={17} />New template</button>} />
    <section className="overview-grid"><article className="metric-card feature-metric"><div className="metric-icon"><FileCheck2 size={20} /></div><span>Available forms</span><strong>{templates.length}</strong><small><Sparkles size={13} />All current versions</small></article><article className="metric-card"><div className="metric-icon mint"><FileText size={20} /></div><span>Total submissions</span><strong>{submissions.length}</strong><small>Across all registers</small></article><article className="metric-card"><div className="metric-icon gold"><CalendarDays size={20} /></div><span>This month</span><strong>{thisMonth}</strong><small>New controlled records</small></article><article className="metric-card"><div className="metric-icon blue"><CheckCircle2 size={20} /></div><span>Approved</span><strong>{approved}</strong><small>{submissions.length ? Math.round((approved / submissions.length) * 100) : 0}% of submissions</small></article></section>
    <section className="section-block"><div className="section-heading"><div><p className="eyebrow">Form library</p><h2>Available forms</h2><p>Use the latest approved version for new records.</p></div><button className="text-button" onClick={() => onRegister()}><ListFilter size={16} />View all registers</button></div><div className="template-grid">{templates.map((template, index) => <article className="template-card" key={template.id}><div className={`document-glyph glyph-${index % 3}`}><FileText size={24} /><span>{template.code}</span></div><div className="template-card-top"><span className="category-pill">{template.category}</span><span className="version-pill">v{template.version}.0</span></div><h3>{template.name}</h3><p>{template.description}</p><div className="template-meta"><span><FileSpreadsheet size={14} />{counts[template.id] || 0} submissions</span><span>Updated {formatDate(template.updatedAt)}</span></div><div className="template-actions"><button className="button primary small" onClick={() => onFill(template)}>Fill new <ChevronRight size={15} /></button><button className="button secondary small" onClick={() => onRegister(template)}>Register</button><button className="icon-button" onClick={() => onRevise(template)} title="Create a new version"><Copy size={16} /></button></div></article>)}<button className="new-template-card" onClick={onBuild}><span><Plus size={22} /></span><strong>Create form template</strong><small>Build a controlled form from fields</small></button></div></section>
    <section className="section-block recent-section"><div className="section-heading"><div><p className="eyebrow">Activity</p><h2>Recent submissions</h2></div>{recent.length > 0 && <button className="text-button" onClick={() => onRegister()}><Eye size={16} />Open registers</button>}</div>{recent.length ? <div className="table-card"><table><thead><tr><th>Reference</th><th>Form</th><th>Submitted by</th><th>Date</th><th>Status</th><th /></tr></thead><tbody>{recent.map((item) => { const template = templates.find((candidate) => candidate.id === item.templateId); return <tr key={item.id} onClick={() => onDetail(item)}><td><strong className="reference">{item.uniqueNumber}</strong></td><td>{template?.name || "Archived template"}</td><td>{item.createdBy}</td><td>{formatDate(item.createdAt)}</td><td><StatusBadge status={item.status} /></td><td><ChevronRight size={16} /></td></tr>; })}</tbody></table></div> : <div className="empty-state compact"><FileCheck2 size={28} /><div><strong>No submissions yet</strong><p>Choose an available form above to create the first controlled record.</p></div></div>}</section>
  </div>;
}

function DocumentLibrary({ templates, versionCount, onBuild, onRegister, onRevise }: { templates: Template[]; versionCount: number; onBuild: () => void; onRegister: (template?: Template) => void; onRevise: (template: Template) => void }) {
  return <div className="content dashboard-page"><PageHeading eyebrow="Controlled document workspace" title="Document library" description="Policies, procedures, governance documents, manuals, and terms of reference are managed separately from operational forms." actions={<button className="button primary" onClick={onBuild}><Plus size={17} />New document</button>} />
    <section className="overview-grid module-overview"><article className="metric-card feature-metric"><div className="metric-icon"><FileText size={20} /></div><span>Controlled documents</span><strong>{templates.length}</strong><small>Current document versions</small></article><article className="metric-card"><div className="metric-icon mint"><FileSpreadsheet size={20} /></div><span>Saved versions</span><strong>{versionCount}</strong><small>All versions in the document register</small></article></section>
    <section className="section-block"><div className="section-heading"><div><p className="eyebrow">Document library</p><h2>Policies, procedures, and governance</h2><p>Generate a controlled PDF for distribution and an editable Word file for future revision.</p></div><button className="text-button" onClick={() => onRegister()}><ListFilter size={16} />Open document register</button></div><div className="template-grid">{templates.map((template, index) => <article className="template-card document-template-card" key={template.id}><div className={`document-glyph glyph-${index % 3}`}><FileText size={24} /><span>{template.code}</span></div><div className="template-card-top"><span className="category-pill">{template.documentMeta.documentType}</span><span className="version-pill">v{template.documentMeta.versionLabel || template.version}</span></div><h3>{template.name}</h3><p>{template.description}</p><div className="template-meta"><span><FileSpreadsheet size={14} />{template.contentSchema.length} content blocks</span><span>{template.documentMeta.classification}</span><span>{template.workflow?.status||"Unassigned legacy"}</span></div><a href="/access" className="text-button">Review & approval history</a><div className="template-actions document-output-actions"><a className="button primary small" href={`/api/document/pdf?id=${template.id}`}><Download size={15} />PDF</a><a className="button secondary small" href={`/api/document/docx?id=${template.id}`}><FileText size={15} />Word</a>{template.sourceImportId && <a className="button secondary small" href={`/api/document/import?id=${template.sourceImportId}`}><UploadCloud size={15} />Original</a>}<button className="icon-button" onClick={() => onRevise(template)} title="Create a new document version"><Copy size={16} /></button></div></article>)}<button className="new-template-card" onClick={onBuild}><span><Plus size={22} /></span><strong>Create controlled document</strong><small>Build a policy, procedure, or governance document</small></button></div></section>
  </div>;
}

function EmptyRegister({ module, onBuild }: { module: ModuleKind; onBuild: () => void }) {
  const isForm = module === "forms";
  return <div className="content register-page"><PageHeading eyebrow={isForm ? "Form registers" : "Document register"} title={isForm ? "No form templates available" : "No controlled documents available"} description={isForm ? "Create a form template before opening its submission register." : "Create a controlled document before opening its separate document register."} actions={<button className="button primary" onClick={onBuild}><Plus size={17} />{isForm ? "Create form" : "Create document"}</button>} /></div>;
}

function Builder({ module, builder, setBuilder, fields, fieldDraft, setFieldDraft, editingIndex, setEditingIndex, onEditField, onSaveField, onDeleteField, onMoveField, draggedIndex, setDraggedIndex, onSave, busy }: { module: ModuleKind; builder: BuilderState; setBuilder: React.Dispatch<React.SetStateAction<BuilderState>>; fields: FormField[]; fieldDraft: FormField; setFieldDraft: React.Dispatch<React.SetStateAction<FormField>>; editingIndex: number | null; setEditingIndex: (value: number | null) => void; onEditField: (index: number) => void; onSaveField: () => void; onDeleteField: (index: number) => void; onMoveField: (from: number, to: number) => void; draggedIndex: number | null; setDraggedIndex: (index: number | null) => void; onSave: () => void; busy: boolean }) {
  const sections = Array.from(new Set(fields.map((field) => field.section).filter(Boolean))); const optionTypes = ["dropdown", "radio"].includes(fieldDraft.type);
  const updateMeta = (changes: Partial<DocumentMeta>) => setBuilder((current) => ({ ...current, documentMeta: { ...current.documentMeta, ...changes } }));
  const isForm = module === "forms";
  return <div className="content builder-page"><PageHeading eyebrow={builder.baseTemplateId ? "New controlled version" : isForm ? "Form designer" : "Document designer"} title={builder.baseTemplateId ? `Revise ${builder.name}` : isForm ? "Build a form template" : "Build a controlled document"} description={isForm ? "Define form metadata, add fillable fields, and arrange them into sections." : "Define controlled-document metadata and content fields in the separate document workspace."} actions={<><button className="button secondary"><Eye size={16} />Preview</button><button className="button primary" onClick={onSave} disabled={busy}>{busy ? <Loader2 className="spin" size={17} /> : <Save size={17} />}Save {isForm ? "form" : "document"}</button></>} />
    <div className="builder-layout"><section className="builder-canvas"><div className="canvas-head"><div><span className="step-chip">01</span><div><h2>Template details</h2><p>Document identity and numbering controls</p></div></div><span className="autosave"><Check size={13} />Draft ready</span></div>
      <div className="metadata-grid"><label className="field-label wide"><span>{isForm ? "Form name" : "Document name"} <b>*</b></span><input value={builder.name} onChange={(event) => setBuilder((current) => ({ ...current, name: event.target.value }))} placeholder={isForm ? "e.g. Equipment Calibration Request" : "e.g. Quality Policy"} /></label><label className="field-label"><span>{isForm ? "Form ID or template code" : "Document ID"} <b>*</b></span><input value={builder.code} onChange={(event) => setBuilder((current) => ({ ...current, code: event.target.value.toUpperCase() }))} placeholder={isForm ? "CCPL-CB-FRM-001" : "CCPL-CB-POL-001"} maxLength={40} /></label><label className="field-label"><span>Category</span><select value={builder.category} onChange={(event) => setBuilder((current) => ({ ...current, category: event.target.value }))}><option>Quality</option><option>Laboratory</option><option>Certification</option><option>Administration</option><option>Human Resources</option></select></label><label className="field-label wide"><span>Description</span><textarea rows={2} value={builder.description} onChange={(event) => setBuilder((current) => ({ ...current, description: event.target.value }))} placeholder={isForm ? "What this form records and when it should be used" : "What this document controls and when it should be used"} /></label><label className="field-label wide"><span>Reference format</span><input className="mono-input" value={builder.numberingPattern} onChange={(event) => setBuilder((current) => ({ ...current, numberingPattern: event.target.value }))} /><small>Tokens: {"{CODE}"}, {"{YYYY}"}, {"{SEQ:4}"}</small></label></div>
      <div className="document-controls"><div className="document-controls-head"><div><ShieldCheck size={18} /><span><strong>{isForm ? "CCPL form output" : "CCPL controlled-document output"}</strong><small>{isForm ? "Forms use a title page followed directly by form content." : "Documents use their separate document workflow and register."}</small></span></div><span className="house-style-pill">{isForm ? "Form format" : "Document format"}</span></div><div className="metadata-grid"><label className="field-label"><span>Type</span>{isForm ? <input value="FORM" readOnly /> : <select value={builder.documentMeta.documentType} onChange={(event) => updateMeta({ documentType: event.target.value })}><option>POLICY</option><option>PROCEDURE</option><option>GOVERNANCE</option><option>MANUAL</option><option>TERMS OF REFERENCE</option><option>GUIDELINE</option></select>}</label><label className="field-label"><span>Version label</span><input value={builder.documentMeta.versionLabel} onChange={(event) => updateMeta({ versionLabel: event.target.value })} placeholder={isForm ? "1.0" : "0.1"} /></label><label className="field-label"><span>Classification</span><select value={builder.documentMeta.classification} onChange={(event) => updateMeta({ classification: event.target.value })}><option>PUBLIC</option><option>INTERNAL</option><option>CONFIDENTIAL</option></select></label><label className="field-label"><span>Document owner</span><input value={builder.documentMeta.documentOwner} onChange={(event) => updateMeta({ documentOwner: event.target.value })} /></label><label className="field-label"><span>Document status</span><input value={builder.documentMeta.documentStatus} onChange={(event) => updateMeta({ documentStatus: event.target.value.toUpperCase() })} /></label><label className="field-label"><span>Effective date</span><input type="date" value={builder.documentMeta.effectiveDate} onChange={(event) => updateMeta({ effectiveDate: event.target.value })} /></label><label className="field-label"><span>Prepared by</span><input value={builder.documentMeta.preparedBy} onChange={(event) => updateMeta({ preparedBy: event.target.value })} /></label>{!isForm && <><label className="field-label"><span>Reviewed by</span><input value={builder.documentMeta.reviewedBy} onChange={(event) => updateMeta({ reviewedBy: event.target.value })} /></label><label className="field-label wide"><span>Approved by</span><input value={builder.documentMeta.approvedBy} onChange={(event) => updateMeta({ approvedBy: event.target.value })} /></label></>}</div></div>
      <div className="layout-choice"><button className="layout-option selected"><span><Sparkles size={19} /></span><div><strong>Generated layout</strong><small>Clean, controlled PDF created automatically</small></div><CheckCircle2 size={18} /></button><button className="layout-option" disabled><span><UploadCloud size={19} /></span><div><strong>Map approved PDF</strong><small>Coordinate mapper planned for phase 2</small></div><span className="soon">Soon</span></button></div>
      <div className="canvas-head field-head"><div><span className="step-chip">02</span><div><h2>{isForm ? "Form fields" : "Document content fields"}</h2><p>{fields.length} field{fields.length === 1 ? "" : "s"} across {sections.length || 0} section{sections.length === 1 ? "" : "s"}</p></div></div></div>
      <div className="field-stack">{fields.length === 0 && <div className="empty-state"><FilePlus2 size={31} /><div><strong>{isForm ? "Your form is ready for its first field" : "Your document is ready for its first content field"}</strong><p>Use the field editor on the right to define the label, type, section, and rules.</p></div></div>}{fields.map((field, index) => { const previousSection = index > 0 ? fields[index - 1].section : ""; return <div key={field.id}>{field.section !== previousSection && <div className="section-divider"><span>{field.section}</span><i /></div>}<article className={`builder-field ${editingIndex === index ? "selected" : ""} ${draggedIndex === index ? "dragging" : ""}`} draggable onDragStart={() => setDraggedIndex(index)} onDragOver={(event) => event.preventDefault()} onDrop={() => { if (draggedIndex !== null) onMoveField(draggedIndex, index); setDraggedIndex(null); }} onClick={() => onEditField(index)}><GripVertical size={17} className="drag-handle" /><div className="field-type-icon">{index + 1}</div><div className="field-summary"><strong>{field.label}{field.required && <b> *</b>}</strong><span>{fieldTypes.find((type) => type.value === field.type)?.label}{field.keySummary ? " • Register column" : ""}</span></div><div className="field-tools"><button onClick={(event) => { event.stopPropagation(); onMoveField(index, index - 1); }} disabled={index === 0} aria-label="Move up"><ArrowUp size={14} /></button><button onClick={(event) => { event.stopPropagation(); onMoveField(index, index + 1); }} disabled={index === fields.length - 1} aria-label="Move down"><ArrowDown size={14} /></button><button className="danger" onClick={(event) => { event.stopPropagation(); onDeleteField(index); }} aria-label="Delete field"><Trash2 size={14} /></button></div></article></div>; })}</div>
    </section><aside className="field-editor"><div className="editor-heading"><div><p className="eyebrow">Field editor</p><h3>{editingIndex === null ? "Add a field" : "Edit field"}</h3></div>{editingIndex !== null && <button className="icon-button" onClick={() => { setEditingIndex(null); setFieldDraft(emptyField()); }}><X size={16} /></button>}</div><label className="field-label"><span>Label <b>*</b></span><input value={fieldDraft.label} onChange={(event) => setFieldDraft((current) => ({ ...current, label: event.target.value }))} placeholder="e.g. Equipment name" /></label><label className="field-label"><span>Field type</span><select value={fieldDraft.type} onChange={(event) => setFieldDraft((current) => ({ ...current, type: event.target.value as FieldType }))}>{fieldTypes.map((type) => <option key={type.value} value={type.value}>{type.label}</option>)}</select></label><label className="field-label"><span>Section</span><input list="section-list" value={fieldDraft.section} onChange={(event) => setFieldDraft((current) => ({ ...current, section: event.target.value }))} /><datalist id="section-list">{sections.map((section) => <option key={section} value={section} />)}</datalist></label>{!["checkbox", "radio"].includes(fieldDraft.type) && <label className="field-label"><span>Placeholder</span><input value={fieldDraft.placeholder || ""} onChange={(event) => setFieldDraft((current) => ({ ...current, placeholder: event.target.value }))} placeholder="Guidance shown to the user" /></label>}{optionTypes && <label className="field-label"><span>Options</span><textarea rows={3} value={(fieldDraft.options || []).join("\n")} onChange={(event) => setFieldDraft((current) => ({ ...current, options: event.target.value.split("\n").filter(Boolean) }))} placeholder="One option per line" /></label>}<label className="field-label"><span>Default value</span><input value={typeof fieldDraft.defaultValue === "boolean" ? "" : fieldDraft.defaultValue || ""} onChange={(event) => setFieldDraft((current) => ({ ...current, defaultValue: event.target.value }))} /></label><div className="toggle-row"><div><strong>Required field</strong><span>Block submission when empty</span></div><button className={`toggle ${fieldDraft.required ? "on" : ""}`} onClick={() => setFieldDraft((current) => ({ ...current, required: !current.required }))}><i /></button></div><div className="toggle-row"><div><strong>Register column</strong><span>Show in summary table</span></div><button className={`toggle ${fieldDraft.keySummary ? "on" : ""}`} onClick={() => setFieldDraft((current) => ({ ...current, keySummary: !current.keySummary }))}><i /></button></div>
      <details className="validation-panel"><summary><span><ShieldCheck size={16} />Validation rules</span><ChevronDown size={16} /></summary><div><label className="field-label"><span>Regular expression</span><input value={fieldDraft.validation?.regex || ""} onChange={(event) => setFieldDraft((current) => ({ ...current, validation: { ...current.validation, regex: event.target.value } }))} placeholder="e.g. ^[A-Z]{3}-\d{4}$" /></label><div className="two-columns"><label className="field-label"><span>Minimum</span><input type="number" value={fieldDraft.validation?.min ?? ""} onChange={(event) => setFieldDraft((current) => ({ ...current, validation: { ...current.validation, min: event.target.value ? Number(event.target.value) : undefined } }))} /></label><label className="field-label"><span>Maximum</span><input type="number" value={fieldDraft.validation?.max ?? ""} onChange={(event) => setFieldDraft((current) => ({ ...current, validation: { ...current.validation, max: event.target.value ? Number(event.target.value) : undefined } }))} /></label></div>{fieldDraft.type === "date" && <div className="two-columns"><label className="field-label"><span>Earliest date</span><input type="date" value={fieldDraft.validation?.minDate || ""} onChange={(event) => setFieldDraft((current) => ({ ...current, validation: { ...current.validation, minDate: event.target.value } }))} /></label><label className="field-label"><span>Latest date</span><input type="date" value={fieldDraft.validation?.maxDate || ""} onChange={(event) => setFieldDraft((current) => ({ ...current, validation: { ...current.validation, maxDate: event.target.value } }))} /></label></div>}</div></details><button className="button primary full" onClick={onSaveField}>{editingIndex === null ? <Plus size={17} /> : <Check size={17} />}{editingIndex === null ? "Add field" : "Update field"}</button>
    </aside></div>
  </div>;
}

function FormControl({ field, value, onChange, disabled = false, error }: { field: FormField; value: string | boolean; onChange: (value: string | boolean) => void; disabled?: boolean; error?: string }) {
  const common = { disabled, id: field.id, name: field.id };
  return <label className={`form-control ${["textarea", "file", "radio"].includes(field.type) ? "wide" : ""} ${error ? "has-error" : ""}`}><span>{field.label}{field.required && <b> *</b>}</span>{field.type === "textarea" && <textarea {...common} rows={4} value={String(value || "")} onChange={(event) => onChange(event.target.value)} placeholder={field.placeholder} />}{field.type === "dropdown" && <select {...common} value={String(value || "")} onChange={(event) => onChange(event.target.value)}><option value="">Select an option</option>{field.options?.map((option) => <option key={option}>{option}</option>)}</select>}{field.type === "radio" && <div className="radio-group">{field.options?.map((option) => <label key={option}><input disabled={disabled} type="radio" name={field.id} checked={value === option} onChange={() => onChange(option)} /><span>{option}</span></label>)}</div>}{field.type === "checkbox" && <label className="checkbox-control"><input disabled={disabled} type="checkbox" checked={Boolean(value)} onChange={(event) => onChange(event.target.checked)} /><span><Check size={13} /></span><em>{field.placeholder || "Yes, this statement applies"}</em></label>}{field.type === "file" && <div className="file-drop"><UploadCloud size={21} /><div><strong>{value ? String(value) : "Choose a supporting file"}</strong><small>PDF, DOCX, XLSX, PNG or JPG</small></div><input disabled={disabled} type="file" onChange={(event) => onChange(event.target.files?.[0]?.name || "")} /></div>}{field.type === "signature" && <div className="signature-input"><input {...common} value={String(value || "")} onChange={(event) => onChange(event.target.value)} placeholder={field.placeholder || "Type full legal name"} /><span>Electronic signature</span></div>}{!["textarea", "dropdown", "radio", "checkbox", "file", "signature"].includes(field.type) && <input {...common} type={field.type} value={String(value || "")} onChange={(event) => onChange(event.target.value)} placeholder={field.placeholder} min={field.validation?.min} max={field.validation?.max} />}{error && <small className="field-error">{error}</small>}</label>;
}

function Filler({ template, values, setValues, errors, onBack, onSubmit, busy }: { template: Template; values: Record<string, string | boolean>; setValues: React.Dispatch<React.SetStateAction<Record<string, string | boolean>>>; errors: Record<string, string>; onBack: () => void; onSubmit: (status: "Draft" | "Submitted") => void; busy: boolean }) {
  const sections = Array.from(new Set(template.fields.map((field) => field.section))); const completed = template.fields.filter((field) => values[field.id] !== undefined && values[field.id] !== "" && values[field.id] !== false).length; const progress = Math.round((completed / Math.max(template.fields.length, 1)) * 100);
  return <div className="content filler-page"><button className="back-button" onClick={onBack}><ArrowLeft size={16} />Back to available forms</button><div className="filler-header"><div className="document-glyph glyph-0"><FileText size={24} /><span>{template.code}</span></div><div><div className="title-badges"><span className="category-pill">{template.category}</span><span className="version-pill">Version {template.version}.0</span></div><h1>{template.name}</h1><p>{template.description}</p></div><div className="progress-card"><div><span>Completion</span><strong>{progress}%</strong></div><i><b style={{ width: `${progress}%` }} /></i><small>{completed} of {template.fields.length} fields ready</small></div></div>
    <div className="form-layout"><section className="form-sheet">{sections.map((section, index) => <div className="form-section" key={section}><div className="form-section-head"><span>{String(index + 1).padStart(2, "0")}</span><div><h2>{section}</h2><p>Complete the fields below. Required items are marked with an asterisk.</p></div></div><div className="form-grid">{template.fields.filter((field) => field.section === section).map((field) => <FormControl key={field.id} field={field} value={values[field.id] ?? ""} error={errors[field.id]} onChange={(value) => setValues((current) => ({ ...current, [field.id]: value }))} />)}</div></div>)}</section><aside className="form-aside"><div className="aside-card"><div className="aside-icon"><ShieldCheck size={19} /></div><h3>Controlled record</h3><p>A permanent reference is assigned when this form is first saved.</p><dl><div><dt>Format</dt><dd>{template.numberingPattern.replace("{CODE}", template.code)}</dd></div><div><dt>Version</dt><dd>{template.version}.0</dd></div><div><dt>Output</dt><dd>Stamped PDF</dd></div></dl></div><div className="aside-tip"><FileCheck2 size={17} /><p><strong>Before submitting</strong>Check required fields and attach any supporting evidence.</p></div></aside></div>
    <div className="sticky-actions"><div><LockKeyhole size={15} />Your authenticated identity will be recorded.</div><div><button className="button secondary" disabled={busy} onClick={() => onSubmit("Draft")}>Save as draft</button><button className="button primary" disabled={busy} onClick={() => onSubmit("Submitted")}>{busy ? <Loader2 size={17} className="spin" /> : <FileCheck2 size={17} />}Submit & issue number</button></div></div>
  </div>;
}

function Register({ module, templates, selectedTemplate, submissions, search, setSearch, statusFilter, setStatusFilter, onTemplateChange, onFill, onDetail }: { module: ModuleKind; templates: Template[]; selectedTemplate: Template; submissions: Submission[]; search: string; setSearch: (value: string) => void; statusFilter: string; setStatusFilter: (value: string) => void; onTemplateChange: (id: string) => void; onFill: (template: Template) => void; onDetail: (submission: Submission) => void }) {
  const isForm = module === "forms";
  const keyFields = selectedTemplate.fields.filter((field) => field.keySummary).slice(0, 3); const rows = submissions.filter((item) => item.templateId === selectedTemplate.id).filter((item) => statusFilter === "All" || item.status === statusFilter).filter((item) => `${item.uniqueNumber} ${item.createdBy} ${Object.values(item.data).join(" ")}`.toLowerCase().includes(search.toLowerCase()));
  const downloadRegister = (excel = false) => {
    const headings = ["Reference", "Submitted date", "Submitted by", "Status", ...keyFields.map((field) => field.label), "Revision"]; const tableRows = rows.map((item) => [item.uniqueNumber, formatDate(item.createdAt), item.createdBy, item.status, ...keyFields.map((field) => String(item.data[field.id] ?? "")), item.revision]); let blob: Blob; let filename: string;
    if (excel) { const escape = (value: unknown) => String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;"); const xmlRows = [headings, ...tableRows].map((row) => `<Row>${row.map((cell) => `<Cell><Data ss:Type="String">${escape(cell)}</Data></Cell>`).join("")}</Row>`).join(""); const xml = `<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="${selectedTemplate.code} Register"><Table>${xmlRows}</Table></Worksheet></Workbook>`; blob = new Blob([xml], { type: "application/vnd.ms-excel" }); filename = `${selectedTemplate.code}-register.xls`; }
    else { const csv = [headings, ...tableRows].map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(",")).join("\n"); blob = new Blob([csv], { type: "text/csv;charset=utf-8" }); filename = `${selectedTemplate.code}-register.csv`; }
    const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url);
  };
  return <div className="content register-page"><PageHeading eyebrow={isForm ? "Form submission register" : "Controlled document register"} title={selectedTemplate.name} description={`Version ${selectedTemplate.version}.0 • ${rows.length} matching record${rows.length === 1 ? "" : "s"}`} actions={isForm ? <button className="button primary" onClick={() => onFill(selectedTemplate)}><Plus size={17} />Fill new</button> : undefined} /><div className="register-switcher"><div className="document-glyph glyph-1"><FileSpreadsheet size={22} /><span>{selectedTemplate.code}</span></div><label><span>{isForm ? "Form register" : "Document register"}</span><select value={selectedTemplate.id} onChange={(event) => onTemplateChange(event.target.value)}>{templates.map((template) => <option key={template.id} value={template.id}>{template.name} - v{template.version}.0</option>)}</select></label><div className="register-stat"><span>Records</span><strong>{submissions.filter((item) => item.templateId === selectedTemplate.id).length}</strong></div><div className="register-stat"><span>Approved</span><strong>{submissions.filter((item) => item.templateId === selectedTemplate.id && item.status === "Approved").length}</strong></div></div>
    <div className="register-toolbar"><label className="search-box"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search reference, submitter, or field data…" /></label><label className="filter-select"><Filter size={16} /><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option>All</option><option>Draft</option><option>Submitted</option><option>Approved</option><option>Archived</option></select></label><div className="export-menu"><button className="button secondary" onClick={() => downloadRegister(false)}><FileDown size={16} />CSV</button><button className="button secondary" onClick={() => downloadRegister(true)}><FileSpreadsheet size={16} />Excel</button></div></div>
    {rows.length ? <div className="table-card register-table"><table><thead><tr><th>Reference</th>{keyFields.map((field) => <th key={field.id}>{field.label}</th>)}<th>Submitted</th><th>Owner</th><th>Status</th><th>Rev.</th><th /></tr></thead><tbody>{rows.map((item) => <tr key={item.id} onClick={() => onDetail(item)}><td><strong className="reference">{item.uniqueNumber}</strong><small>Created {formatDate(item.createdAt)}</small></td>{keyFields.map((field) => <td key={field.id}>{String(item.data[field.id] ?? "-")}</td>)}<td>{formatDate(item.updatedAt)}</td><td><span className="owner-cell"><span>{initials(item.createdBy)}</span>{item.createdBy}</span></td><td><StatusBadge status={item.status} /></td><td>R{item.revision}</td><td><button className="icon-button"><ChevronRight size={16} /></button></td></tr>)}</tbody></table></div> : <div className="empty-state register-empty"><Search size={29} /><div><strong>No matching records</strong><p>{isForm ? "Adjust the search or status filter, or create a new submission for this form." : "This controlled document has no records in the separate document register."}</p></div></div>}</div>;
}

function SubmissionDetail({ template, submission, audit, values, setValues, errors, editing, setEditing, status, setStatus, onBack, onSave, busy }: { template: Template; submission: Submission; audit: AuditItem[]; values: Record<string, string | boolean>; setValues: React.Dispatch<React.SetStateAction<Record<string, string | boolean>>>; errors: Record<string, string>; editing: boolean; setEditing: (value: boolean) => void; status: string; setStatus: (value: string) => void; onBack: () => void; onSave: () => void; busy: boolean }) {
  const sections = Array.from(new Set(template.fields.map((field) => field.section)));
  return <div className="content detail-page"><button className="back-button" onClick={onBack}><ArrowLeft size={16} />Back to register</button><PageHeading eyebrow="Controlled submission" title={submission.uniqueNumber} description={`${template.name} | Version ${template.version}.0`} actions={<><a className="button secondary" href={submission.pdfPath}><Download size={16} />Download PDF</a>{editing ? <><button className="button ghost" onClick={() => { setValues({ ...submission.data }); setStatus(submission.status); setEditing(false); }}>Cancel</button><button className="button primary" onClick={onSave} disabled={busy}>{busy ? <Loader2 className="spin" size={16} /> : <Save size={16} />}Save revision</button></> : <button className="button primary" onClick={() => setEditing(true)}><Edit3 size={16} />Edit record</button>}</>} /><div className="detail-summary"><div><span>Current status</span>{editing ? <select value={status} onChange={(event) => setStatus(event.target.value)}><option>Draft</option><option>Submitted</option><option>Approved</option><option>Archived</option></select> : <StatusBadge status={submission.status} />}</div><div><span>Submitted by</span><strong>{submission.createdBy}</strong></div><div><span>Created</span><strong>{formatDate(submission.createdAt, true)}</strong></div><div><span>Last updated</span><strong>{formatDate(submission.updatedAt, true)}</strong></div><div><span>Revision</span><strong>R{submission.revision}</strong></div></div><div className="detail-layout"><section className="detail-sheet">{sections.map((section) => <div className="detail-section" key={section}><h2>{section}</h2><div className="detail-grid">{template.fields.filter((field) => field.section === section).map((field) => editing ? <FormControl key={field.id} field={field} value={values[field.id] ?? ""} error={errors[field.id]} onChange={(value) => setValues((current) => ({ ...current, [field.id]: value }))} /> : <div className={`detail-value ${field.type === "textarea" ? "wide" : ""}`} key={field.id}><span>{field.label}</span><strong>{typeof submission.data[field.id] === "boolean" ? (submission.data[field.id] ? "Yes" : "No") : String(submission.data[field.id] || "-")}</strong></div>)}</div></div>)}</section><aside className="audit-card"><div className="audit-head"><History size={18} /><div><h3>Audit trail</h3><p>Immutable change history</p></div></div><div className="audit-list">{audit.length ? audit.map((item) => <article key={item.id}><span className="audit-dot" /><div><strong>{item.summary}</strong><p>{item.changed_by}</p><time>{formatDate(item.timestamp, true)}</time></div></article>) : <div className="audit-loading">No additional revisions</div>}</div><div className="audit-lock"><LockKeyhole size={15} />Audit entries cannot be edited.</div></aside></div></div>;
}
